[package]
name = "openvm-sha256-air"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
openvm-circuit-primitives = { workspace = true }
openvm-stark-backend = { workspace = true }

rand.workspace = true

[dev-dependencies]
p3-symmetric = { workspace = true }
test-case = "3.3.1"
ark-ff = { version = "^0.4.0", default-features = false }

[features]
default = ["parallel"]
parallel = ["openvm-stark-backend/parallel"]
