[package]
name = "ax-ecc-execution"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
halo2curves-axiom = "0.7.0"
itertools.workspace = true

[dev-dependencies]
rand.workspace = true
rng = "0.1.0"
