name: Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  coverage:
    runs-on: 
      - runs-on=${{ github.run_id }}
      - runner=16cpu-linux-arm64
      - tag=coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain (nightly)
        run: rustup toolchain install nightly --component llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Run coverage
        run: cargo llvm-cov --html --lcov --output-path=coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/